---

- name: Fetch the latest ports tree (FreeBSD)
  command: /usr/sbin/portsnap fetch
  register: fetch_result
  changed_when: "'No updates needed.' in fetch_result.stdout"
  tags: autologic_osupdate_task_update_ports_freebsd

- name: Extract the latest port tree (FreeBSD)
  command: /usr/sbin/portsnap update
  register: update_result
  changed_when: "'Ports tree is already up to date.' in update_result.stdout"
  tags: autologic_osupdate_task_update_ports_freebsd
